# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarcekModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('picture', models.URLField()),
                ('price_vat', models.CharField(max_length=25)),
            ],
        ),
    ]
